title: Nicolas Pedraza B.
logo: NicoPhoto-modified.png
description: Tool Expertise: Programming Languages(Python, SQL), Database Systems(SQL, NoSQL), Data Pipelines and Workflows (Airflow), REST API development, ETL tools(NiFi,), Big Data tools and technologies(Hadoop, Spark, Kafka), Algorithms and Data Structures, and Machine Learning
