title: Nicolas Pedraza
logo: NicoPhoto-modified.png
description: 
- P.Professional Certificate Data Engineering MIT xPro (Feb 2025)
- B.S Mechanical Engineering Loyola Marymount University (Dec 2024)
theme: jekyll-theme-minimal
