title: Nicolas Pedraza B.
logo: NicoPhoto-modified.png
description: 
- Data Engineering MIT xPro (Feb 2025)
- Mechanical Engineering Loyola Marymount University (Dec 2024)
theme: jekyll-theme-minimal
